<?php

declare(strict_types=1);

namespace Adeliom\SyliusHappyCMSPlugin\Services\Seo;

use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class BreadcrumbCollection
{
    /** @var array <int, mixed> */
    protected array $items = [];

    protected UrlGeneratorInterface $generator;

    /**
     * Adds new simple breadcrumb item. Leave target empty to create a breadcrumb item without a link.
     */
    public function addSimpleItem(string $linkName, string $target = null, ?object $object = null): void
    {
        $this->items[] = ['linkName' => $linkName, 'target' => $target, 'object' => $object];
    }

    /**
     * Adds new breadcrumb item where target is being generated by the url generator.
     */
    /**
     * @param array{
     *     route: string,
     *     params?: array<string, mixed>
     * } $route
     */
    public function addRouteItem(string $linkName, array $route, ?object $object = null): void
    {
        $url = isset($route['params']) ? $this->generator->generate($route['route'], $route['params']) :
            $this->generator->generate($route['route']);

        $this->addSimpleItem($linkName, $url, $object);
    }

    /**
     * Return all Breadcrumbs.
     *
     * @return  array<int, mixed> $route
     */
    public function getItems(): array
    {
        return $this->items;
    }

    public function setGenerator(UrlGeneratorInterface $generator): void
    {
        $this->generator = $generator;
    }
}
