services:

  # AI Services
  Adeliom\SyliusHappyCMSPlugin\Services\AI\AIBundleDetector:
    public: true
    arguments:
      - '@kernel'
      
  sylius.happy_cms.ai.bundle_detector:
      alias: Adeliom\SyliusHappyCMSPlugin\Services\AI\AIBundleDetector


  Adeliom\SyliusHappyCMSPlugin\Services\AI\BlockSchemaSerializer:
    public: true
    arguments:
      - '@sylius.happy_cms.block_collection'
      - '@form.factory'
      - '@translator'

  sylius.happy_cms.ai.block_schema_serializer:
    alias: Adeliom\SyliusHappyCMSPlugin\Services\AI\BlockSchemaSerializer

  Adeliom\SyliusHappyCMSPlugin\Services\AI\BlockContentGenerator:
    public: true
    arguments:
      - '@sylius.happy_cms.ai.block_schema_serializer'
      - '@?Symfony\AI\Agent\AgentInterface'  # Optional: will be null if AI bundle is not configured
      - '%sylius_happy_cms.page_builder.ai_generate_content_prompt%'

  sylius.happy_cms.ai.block_content_generator:
    alias: Adeliom\SyliusHappyCMSPlugin\Services\AI\BlockContentGenerator

  sylius.happy_cms.ai.show_block_list:
      class: Adeliom\SyliusHappyCMSPlugin\Command\AI\ShowBlockSchemaCommand
      arguments:
          - '@sylius.happy_cms.ai.block_schema_serializer'
      tags:
          - { name: 'console.command' }
