services:

  sylius.happy_cms.maker.make_block:
    class: Adeliom\SyliusHappyCMSPlugin\Maker\Block\MakeBlock
    public: false
    arguments:
      - '@maker.file_manager'
    tags:
      - { name: maker.command }

  sylius.happy_cms.maker.make_happy_cms:
    class: Adeliom\SyliusHappyCMSPlugin\Maker\CMS\MakeHappyCMS
    public: false
    arguments:
      - '@doctrine'
      - '@parameter_bag'
    tags:
      - { name: maker.command }

  sylius.happy_cms.maker.happy_cms_init_default_files:
    class: Adeliom\SyliusHappyCMSPlugin\Maker\InstallDefaultFiles
    public: false
    arguments:
      - '@parameter_bag'
    tags:
      - { name: maker.command }

  sylius.happy_cms.shared_block.maker.make_shared_block:
    class: Adeliom\SyliusHappyCMSPlugin\Maker\SharedBlock\MakeSharedBlock
    public: false
    arguments:
      - '@maker.file_manager'
    tags:
      - { name: maker.command }
