services:
    happy_cms_menu.menu.repository:
        class: Adeliom\SyliusHappyCMSPlugin\Repository\Menu\MenuItemRepository
        arguments:
            - '@doctrine'
            - Adeliom\SyliusHappyCMSPlugin\Entity\Menu\MenuInterface
        calls:
            - [ 'setConfig', [ '%sylius_happy_cms.menu.cache%' ] ]
        tags: [ doctrine.repository_service ]

    happy_cms_menu.menu_item.repository:
        class: Adeliom\SyliusHappyCMSPlugin\Repository\Menu\MenuItemRepositoryInterface
        arguments:
            - '@doctrine'
            - Adeliom\SyliusHappyCMSPlugin\Entity\Menu\MenuItemInterface
        calls:
            - [ 'setConfig', [ '%sylius_happy_cms.menu.cache%' ] ]
        tags: [ doctrine.repository_service ]

    Adeliom\SyliusHappyCMSPlugin\EventListener\Menu\MenuCreationListener:
        arguments:
            - '@sylius.locale_provider'
            - '@translator'
            - '@parameter_bag'
        tags:
            - # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                event: 'prePersist'
                entity: Adeliom\SyliusHappyCMSPlugin\Entity\Menu\Menu
                lazy: true

    Adeliom\SyliusHappyCMSPlugin\Twig\Menu\MenuExtension:
        public: true
        autowire: true
        arguments:
            - '@twig'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }

    Adeliom\SyliusHappyCMSPlugin\Controller\MenuItem\MenuItemController:
        public: true
        autowire: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@twig'
            - '@router'
        tags:
            - controller.service_arguments
