services:
  _defaults:
    autowire: true
    autoconfigure: true

  happy_cms.page.twig.extension:
    class: Adeliom\SyliusHappyCMSPlugin\Twig\Page\PageExtension
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: twig.extension }

  Adeliom\SyliusHappyCMSPlugin\Controller\Page\PageController:
    arguments:
      - '@sylius.happy_cms.plugin.services.render'
      - '@router'
      - '@translator'
      - '@doctrine.orm.entity_manager'
    public: true

  Adeliom\SyliusHappyCMSPlugin\Controller\PageBuilder\PageBuilderController:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@parameter_bag'
    public: true
