parameters:
  cmf_routing.dynamic.persistence.orm.route_class: 'Adeliom\SyliusHappyCMSPlugin\Entity\Cmf\Route'

cmf_routing:
    chain:
        routers_by_id:
            router.default:             100
            cmf_routing.dynamic_router: 50
    dynamic:
        persistence:
            orm:
                enabled: true
        locales:
            - en_US
        match_implicit_locale: false
        controllers_by_class:
            Symfony\Cmf\Component\Routing\RedirectRouteInterface: cmf_routing.redirect_controller:redirectAction
            Symfony\Cmf\Component\Routing\RouteReferrersInterface: sylius.happy_cms.plugin.controller.render::renderAction
