doctrine:
  dbal:
    types:
      adeliom_happy_cms_flexible_content_type: Adeliom\SyliusHappyCMSPlugin\Doctrine\FlexibleContentType
      happy_cms_media_type: Adeliom\SyliusHappyCMSPlugin\Doctrine\MediaType
  orm:

    mappings:
#      SyliusHappyCMSPlugin:
#        is_bundle: true
#        type: xml
#        dir: 'src/Resources/config/doctrine/mapping'
    resolve_target_entities:
#      Adeliom\SyliusHappyCMSPlugin\Entity\Page\PageInterface: "%sylius_happy_cms.page.model%"
#      Adeliom\SyliusHappyCMSPlugin\Entity\Page\PageTranslationInterface: "%sylius_happy_cms.page.model_translation%"
      Adeliom\SyliusHappyCMSPlugin\Entity\Seo\SeoInterface: Adeliom\SyliusHappyCMSPlugin\Entity\Seo\Seo
#      Adeliom\SyliusHappyCMSPlugin\Entity\Media\MediaInterface: "%sylius_happy_cms.media.model%"
#      Adeliom\SyliusHappyCMSPlugin\Entity\Media\FolderInterface: "%sylius_happy_cms.folder.model%"
#      Adeliom\SyliusHappyCMSPlugin\Entity\Menu\MenuInterface: "%sylius_happy_cms.menu.model%"
#      Adeliom\SyliusHappyCMSPlugin\Entity\Menu\MenuItemInterface: "%sylius_happy_cms.menu_item.model%"
#      Adeliom\SyliusHappyCMSPlugin\Entity\Menu\MenuItemTranslationInterface: "%sylius_happy_cms.menu_item.model_translation%"
#      Adeliom\SyliusHappyCMSPlugin\Entity\Config\ConfigInterface: "%sylius_happy_cms.config.model%"
#      Adeliom\SyliusHappyCMSPlugin\Entity\Config\ConfigTranslationInterface: "%sylius_happy_cms.config.model_translation%"
#      Adeliom\SyliusHappyCMSPlugin\Entity\SharedBlock\SharedBlockInterface: "%sylius_happy_cms.shared_block.model%"
#      Adeliom\SyliusHappyCMSPlugin\Entity\SharedBlock\SharedBlockTranslationInterface: "%sylius_happy_cms.shared_block.model_translation%"


