#sylius_resource:
#  resources:
#    sylius_happy_cms.page:
#      driver: doctrine/orm
#      classes:
#        model: "%sylius_happy_cms.page.model%"
#        controller: "%sylius_happy_cms.page.controller%"
#        repository: "%sylius_happy_cms.page.repository%"
#        form: "%sylius_happy_cms.page.page_admin%"
#      translation:
#        classes:
#          model: "%sylius_happy_cms.page.model_translation%"
#          controller: "%sylius_happy_cms.page.controller_translation%"
#          form: "%sylius_happy_cms.page.page_admin%"
#    sylius_happy_cms.config:
#      driver: doctrine/orm
#      classes:
#        model: "%sylius_happy_cms.config.model%"
#        controller: "%sylius_happy_cms.config.controller%"
#        repository: "%sylius_happy_cms.config.repository%"
#        form: "%sylius_happy_cms.config.config_admin%"
#      translation:
#        classes:
#          model: "%sylius_happy_cms.config.model_translation%"
#          controller: "%sylius_happy_cms.config.controller_translation%"
#          form: "%sylius_happy_cms.config.config_admin%"
#    sylius_happy_cms.menu:
#      driver: doctrine/orm
#      classes:
#        model: "%sylius_happy_cms.menu.model%"
#        controller: "%sylius_happy_cms.menu.controller%"
#        repository: "%sylius_happy_cms.menu.repository%"
#        form: "%sylius_happy_cms.menu.menu_admin%"
#    sylius_happy_cms.menu_item:
#      driver: doctrine/orm
#      classes:
#        model: "%sylius_happy_cms.menu_item.model%"
#        controller: "%sylius_happy_cms.menu_item.controller%"
#        repository: "%sylius_happy_cms.menu_item.repository%"
#        form: "%sylius_happy_cms.menu_item.menu_item_admin%"
#      translation:
#        classes:
#          model: "%sylius_happy_cms.menu_item.model_translation%"
#          controller: "%sylius_happy_cms.menu_item.controller_translation%"
#          form: "%sylius_happy_cms.menu_item.menu_item_admin%"
#    sylius_happy_cms.shared_block:
#      driver: doctrine/orm
#      classes:
#        model: "%sylius_happy_cms.shared_block.model%"
#        controller: "%sylius_happy_cms.shared_block.controller%"
#        repository: "%sylius_happy_cms.shared_block.repository%"
#        form: "%sylius_happy_cms.shared_block.shared_block_admin%"
#      translation:
#        classes:
#          model: "%sylius_happy_cms.shared_block.model_translation%"
#          controller: "%sylius_happy_cms.shared_block.controller_translation%"
#          form: "%sylius_happy_cms.shared_block.shared_block_admin%"
#    sylius_happy_cms.media:
#      driver: doctrine/orm
#      classes:
#        model: "%sylius_happy_cms.media.model%"
#        repository: "%sylius_happy_cms.media.repository%"
#    sylius_happy_cms.media_folder:
#      driver: doctrine/orm
#      classes:
#        model: "%sylius_happy_cms.folder.model%"
#        repository: "%sylius_happy_cms.folder.repository%"
