imports:
  - { resource: "./packages/cmf_routing.yaml" }
  - { resource: "./packages/doctrine.yaml" }
  - { resource: "./packages/sylius_ui.yaml" }
  - { resource: "./packages/sylius_happy_cms.yaml" }
  #- { resource: "./packages/sylius_resource.yaml" }
  - { resource: "./packages/flysystem.yaml" }

parameters:
  sylius_happy_cms.page.model: Adeliom\SyliusHappyCMSPlugin\Entity\Page\Page
  sylius_happy_cms.page.model_translation: Adeliom\SyliusHappyCMSPlugin\Entity\Page\PageTranslation
  sylius_happy_cms.page.repository: Adeliom\SyliusHappyCMSPlugin\Repository\Page\PageRepository
  sylius_happy_cms.page.controller: Adeliom\SyliusEasyCrudPlugin\Controller\SyliusCrudResourceController
  sylius_happy_cms.page.controller_translation: Adeliom\SyliusEasyCrudPlugin\Controller\SyliusCrudResourceController
  sylius_happy_cms.page.page_admin: Adeliom\SyliusHappyCMSPlugin\Admin\Page\PageAdmin

  sylius_happy_cms.config.model: Adeliom\SyliusHappyCMSPlugin\Entity\Config\Config
  sylius_happy_cms.config.model_translation: Adeliom\SyliusHappyCMSPlugin\Entity\Config\ConfigTranslation
  sylius_happy_cms.config.repository: Adeliom\SyliusHappyCMSPlugin\Repository\Config\ConfigRepository
  sylius_happy_cms.config.controller: Adeliom\SyliusEasyCrudPlugin\Controller\SyliusCrudResourceController
  sylius_happy_cms.config.controller_translation: Adeliom\SyliusEasyCrudPlugin\Controller\SyliusCrudResourceController
  sylius_happy_cms.config.config_admin: Adeliom\SyliusHappyCMSPlugin\Admin\Config\ConfigAdmin

  sylius_happy_cms.folder.model: Adeliom\SyliusHappyCMSPlugin\Entity\Media\Folder
  sylius_happy_cms.folder.repository: Adeliom\SyliusHappyCMSPlugin\Repository\Media\FolderRepository

  sylius_happy_cms.media.model: Adeliom\SyliusHappyCMSPlugin\Entity\Media\Media
  sylius_happy_cms.media.repository: Adeliom\SyliusHappyCMSPlugin\Repository\Media\MediaRepository

  sylius_happy_cms.menu.model: Adeliom\SyliusHappyCMSPlugin\Entity\Menu\Menu
  sylius_happy_cms.menu.repository: Adeliom\SyliusHappyCMSPlugin\Repository\Menu\MenuRepository
  sylius_happy_cms.menu.controller: Adeliom\SyliusEasyCrudPlugin\Controller\SyliusCrudResourceController
  sylius_happy_cms.menu.menu_admin: Adeliom\SyliusHappyCMSPlugin\Admin\Menu\MenuAdmin

  sylius_happy_cms.menu_item.model: Adeliom\SyliusHappyCMSPlugin\Entity\Menu\MenuItem
  sylius_happy_cms.menu_item.model_translation: Adeliom\SyliusHappyCMSPlugin\Entity\Menu\MenuItemTranslation
  sylius_happy_cms.menu_item.repository: Adeliom\SyliusHappyCMSPlugin\Repository\Menu\MenuItemRepository
  sylius_happy_cms.menu_item.controller: Adeliom\SyliusEasyCrudPlugin\Controller\SyliusCrudResourceController
  sylius_happy_cms.menu_item.controller_translation: Adeliom\SyliusEasyCrudPlugin\Controller\SyliusCrudResourceController
  sylius_happy_cms.menu_item.menu_item_admin: Adeliom\SyliusHappyCMSPlugin\Admin\Menu\MenuItemAdmin

  sylius_happy_cms.shared_block.model: Adeliom\SyliusHappyCMSPlugin\Entity\SharedBlock\SharedBlock
  sylius_happy_cms.shared_block.model_translation: Adeliom\SyliusHappyCMSPlugin\Entity\SharedBlock\SharedBlockTranslation
  sylius_happy_cms.shared_block.repository: Adeliom\SyliusHappyCMSPlugin\Repository\SharedBlock\SharedBlockRepository
  sylius_happy_cms.shared_block.controller: Adeliom\SyliusEasyCrudPlugin\Controller\SyliusCrudResourceController
  sylius_happy_cms.shared_block.controller_translation: Adeliom\SyliusEasyCrudPlugin\Controller\SyliusCrudResourceController
  sylius_happy_cms.shared_block.shared_block_admin: Adeliom\SyliusHappyCMSPlugin\Admin\SharedBlock\SharedBlockAdmin

  sylius_happy_cms.seo.model: Adeliom\SyliusHappyCMSPlugin\Entity\Seo\Seo
