imports:
  - { resource: "./packages/cmf_routing.yaml" }
  - { resource: "./packages/doctrine.yaml" }
  - { resource: "./packages/sylius_ui.yaml" }
  - { resource: "./packages/sylius_happy_cms.yaml" }
  - { resource: "./packages/sylius_resource.yaml" }
  - { resource: "./packages/flysystem.yaml" }
