sylius_happy_cms_admin_shared_block_select:
  controller: Adeliom\SyliusHappyCMSPlugin\Controller\SharedBlock\SharedBlockController::select
  path: /admin/shared-blocks/select
  methods: ['GET']

sylius_happy_cms_admin_menu_item_index:
  path: /admin/menu-items/
  methods: [ GET ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\MenuItem\MenuItemController::indexAction
    route: sylius_happy_cms_admin_menu_index
    permanent: true

sylius_happy_cms_admin_page_clear_cache:
  path: /admin/pages/clear-cache
  methods: [ GET ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\Page\PageController::clearCacheAction
    _sylius:
      template: $template
      menu: $menu
      vars: $vars
      permission: true

sylius_happy_cms_admin_flexible_content_preview_block:
  path: /admin/pages/flexible-content/preview-block
  methods: [ GET ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\Page\PageController::blockPreviewAction
    _sylius:
      data: $data
      block: $block
      permission: true

sylius_happy_cms_admin_page_builder:
  path: /admin/happy-cms-builder/{resource}/{id}
  methods: [ GET, POST ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\PageBuilder\PageBuilderController::builderAction
    _sylius:
      template: '@SyliusHappyCMSPlugin/admin/page_builder/index.html.twig'
      permission: false
  requirements:
    id: '\d+'

sylius_happy_cms_admin_page_builder_block_edit:
  path: /admin/happy-cms-builder/{resource}/{id}/block/{blockId}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\PageBuilder\PageBuilderController::blockEditAction
    _sylius:
      template: '@SyliusHappyCMSPlugin/admin/page_builder/block_edit.html.twig'
      permission: false
  requirements:
    id: '\d+'
    blockId: '\d+'
