sylius_happy_cms_admin_shared_block_select:
  controller: Adeliom\SyliusHappyCMSPlugin\Controller\SharedBlock\SharedBlockController::select
  path: /admin/shared-blocks/select
  methods: ['GET']

sylius_happy_cms_admin_menu_item_index:
  path: /admin/menu-items/
  methods: [ GET ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\MenuItem\MenuItemController::indexAction
    route: sylius_happy_cms_admin_menu_index
    permanent: true

sylius_happy_cms_admin_menu_item_tree:
  path: /admin/menu-items/tree
  methods: [ GET ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\MenuItem\MenuItemController::treeAction
    _sylius:
      template: $template
      menu: $menu
      vars: $vars
      permission: true

sylius_happy_cms_admin_menu_item_update_move_up:
  path: /admin/menu-items/{id}/move-up
  methods: [ PUT ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\MenuItem\MenuItemController::moveUpAction
    _format: json
    _sylius:
      permission: true

sylius_happy_cms_admin_menu_item_update_move_down:
  path: /admin/menu-items/{id}/move-down
  methods: [ PUT ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\MenuItem\MenuItemController::moveDownAction
    _format: json
    _sylius:
      permission: true

sylius_happy_cms_admin_flexible_content_preview_block:
  path: /admin/pages/flexible-content/preview-block
  methods: [ GET ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\Page\PageResourceController::blockPreviewAction
    _sylius:
      data: $data
      block: $block
      permission: true

sylius_happy_cms_admin_page_tree:
  path: /admin/pages/tree
  methods: [ GET ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\Page\PageResourceController::treeAction
    _sylius:
      template: $template
      menu: $menu
      vars: $vars
      permission: true

sylius_happy_cms_admin_page_update_move_up:
  path: /admin/pages/{id}/move-up
  methods: [ PUT ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\Page\PageResourceController::moveUpAction
    _format: json
    _sylius:
      permission: true

sylius_happy_cms_admin_page_update_move_down:
  path: /admin/pages/{id}/move-down
  methods: [ PUT ]
  defaults:
    _controller: Adeliom\SyliusHappyCMSPlugin\Controller\Page\PageResourceController::moveDownAction
    _format: json
    _sylius:
      permission: true
