imports:
  - { resource: services/pages.yaml }
  - { resource: services/seo.yaml }
  - { resource: services/menu.yaml }
  - { resource: services/block.yaml }
  - { resource: services/maker.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Adeliom\SyliusHappyCMSPlugin\ContextProvider\CreateSharedBlockContextProvider:
    arguments:
      - '@sylius.happy_cms.shared_block.block_collection'
    tags:
      - { name: sylius.ui.template_event.context_provider }

  sylius.happy_cms.plugin.listener.entity_route_indexer:
    class: Adeliom\SyliusHappyCMSPlugin\EventListener\EntityRouteIndexer
    arguments:
      - '@cmf_routing.orm_content_repository'
      - "@parameter_bag"
    tags:
      -   name: 'doctrine.event_listener'
          event: 'postPersist'
          priority: 500
          connection: 'default'
      -   name: 'doctrine.event_listener'
          event: 'postUpdate'
          priority: 500
          connection: 'default'

  Adeliom\SyliusHappyCMSPlugin\Services\Cmf\RouteRenderService:
    alias: sylius.happy_cms.plugin.services.render

  Adeliom\SyliusHappyCMSPlugin\Repository\Menu\MenuRepositoryInterface:
    alias: happy_cms_menu.menu_item.repository

  Adeliom\SyliusHappyCMSPlugin\Repository\Menu\MenuItemRepositoryInterface:
    alias: happy_cms_menu.menu.repository

  Adeliom\SyliusHappyCMSPlugin\Repository\Page\PageRepositoryInterface:
    alias: happy_cms_page.page.repository

  Adeliom\SyliusHappyCMSPlugin\Repository\Cmf\RouteRepositoryInterface:
    alias: happy_cms_page.route.repository

  sylius.happy_cms.plugin.services.render:
    class: Adeliom\SyliusHappyCMSPlugin\Services\Cmf\RouteRenderService
    arguments:
      - "@router"
      - "@sylius.resource_controller.request_configuration_factory"
      - "@twig"
      - "@event_dispatcher"
      - "@happy_cms_seo.breadcrumb"
      - "@kernel"
      - "@doctrine.orm.entity_manager"
      - "@parameter_bag"
    public: true

  sylius.happy_cms.plugin.controller.render:
    class: Adeliom\SyliusHappyCMSPlugin\Controller\Routing\RenderController
    arguments:
      - "@sylius.happy_cms.plugin.services.render"
    public: true

  Adeliom\SyliusHappyCMSPlugin\Asset\AssetHappyCMSPackage:
    tags:
      -   assets.package: { package: 'sylius.happy.cms.assets.package' }

  Adeliom\SyliusHappyCMSPlugin\Security\ContentDocumentVoter:
    tags:
      - "security.voter"

  Adeliom\SyliusHappyCMSPlugin\Routing\MediaLoader:
    tags: [ routing.loader ]


  # pages
  # ===============================


  # todo interface alias
  sylius.happy_cms.page.all_pages:
    class: Adeliom\SyliusHappyCMSPlugin\Doctrine\Query\Page\AllPages
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@sylius_admin.context.locale.admin_based"
      - "@sylius.translation_locale_provider"

  # todo interface alias
  sylius.happy_cms.admin.page_tree.tree:
    class: Adeliom\SyliusHappyCMSPlugin\Twig\Components\PageTree\TreeComponent
    arguments:
      - "@sylius.happy_cms.page.all_pages"
    tags:
      - { name: sylius.live_component.admin, key: happycms-page-tree-tree }

  # todo interface alias
  sylius.happy_cms.admin.page_tree.delete:
    class: Adeliom\SyliusHappyCMSPlugin\Twig\Components\PageTree\DeleteComponent
    arguments:
      - "@security.csrf.token_manager"
    tags:
      - { name: sylius.live_component.admin, key: happycms-page-tree-delete, template: '@SyliusHappyCMSPlugin/page/crud/tree/components/delete.html.twig' }

  # menu
  # ===============================


  # todo interface alias
  sylius.happy_cms.menu_item.all_menu_items:
    class: Adeliom\SyliusHappyCMSPlugin\Doctrine\Query\Menu\AllMenuItems
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@sylius_admin.context.locale.admin_based"
      - "@sylius.translation_locale_provider"

  # todo interface alias
  sylius.happy_cms.admin.menu_item_tree.tree:
    class: Adeliom\SyliusHappyCMSPlugin\Twig\Components\MenuItemTree\TreeComponent
    arguments:
      - "@sylius.happy_cms.menu_item.all_menu_items"
    tags:
      - { name: sylius.live_component.admin, key: happycms-menu-item-tree-tree }

  # todo interface alias
  sylius.happy_cms.admin.menu_item_tree.delete:
    class: Adeliom\SyliusHappyCMSPlugin\Twig\Components\MenuItemTree\DeleteComponent
    arguments:
      - "@security.csrf.token_manager"
    tags:
      - { name: sylius.live_component.admin, key: happycms-menu-item-tree-delete, template: '@SyliusHappyCMSPlugin/menu_item/crud/tree/components/delete.html.twig' }

  sylius.happy_cms.plugin.listener.redirection_manager:
    class: Adeliom\SyliusHappyCMSPlugin\Services\Cmf\RedirectionManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@parameter_bag'

  Adeliom\SyliusHappyCMSPlugin\Services\Cmf\RedirectionManagerInterface:
    alias: sylius.happy_cms.plugin.listener.redirection_manager

  sylius.happy_cms.exception_listener:
    class: Adeliom\SyliusHappyCMSPlugin\EventListener\ExceptionListener
    arguments:
        - '@sylius.happy_cms.plugin.listener.redirection_manager'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
