imports:
  - { resource: services/pages.yaml }
  - { resource: services/seo.yaml }
  - { resource: services/menu.yaml }
  - { resource: services/block.yaml }
  - { resource: services/maker.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Adeliom\SyliusHappyCMSPlugin\ContextProvider\CreateSharedBlockContextProvider:
    arguments:
      - '@sylius.happy_cms.shared_block.block_collection'
    tags:
      - { name: sylius.ui.template_event.context_provider }

  sylius.happy_cms.plugin.listener.entity_route_indexer:
    class: Adeliom\SyliusHappyCMSPlugin\EventListener\EntityRouteIndexer
    arguments:
      - '@cmf_routing.orm_content_repository'
    tags:
      -   name: 'doctrine.event_listener'
          event: 'postPersist'
          priority: 500
          connection: 'default'
      -   name: 'doctrine.event_listener'
          event: 'postUpdate'
          priority: 500
          connection: 'default'

  Adeliom\SyliusHappyCMSPlugin\Services\RouteRenderService:
    alias: sylius.happy_cms.plugin.services.render

  sylius.happy_cms.plugin.services.render:
    class: Adeliom\SyliusHappyCMSPlugin\Services\RouteRenderService
    arguments:
      - "@router"
      - "@sylius.resource_controller.request_configuration_factory"
      - "@twig"
      - "@event_dispatcher"
    public: true

  sylius.happy_cms.plugin.controller.render:
    class: Adeliom\SyliusHappyCMSPlugin\Controller\Routing\RenderController
    arguments:
      - "@sylius.happy_cms.plugin.services.render"
    public: true

  Adeliom\SyliusHappyCMSPlugin\Asset\AssetHappyCMSPackage:
    tags:
      -   assets.package: { package: 'sylius.happy.cms.assets.package' }

  Adeliom\SyliusHappyCMSPlugin\Security\ContentDocumentVoter:
    tags:
      - "security.voter"

  Adeliom\SyliusHappyCMSPlugin\Routing\MediaLoader:
    tags: [ routing.loader ]


  # pages
  # ===============================



  # seo
  # ===============================
